const mmio = @import("mmio");
const types = @import("../../types.zig");

/// VREFBUF
pub const VREFBUF = extern struct {
    /// VREFBUF control and status register
    /// offset: 0x00
    VREFBUF_CSR: mmio.Mmio(packed struct(u32) {
        /// Voltage reference buffer mode enable This bit is used to enable the voltage reference buffer mode.
        ENVR: u1,
        /// High impedance mode This bit controls the analog switch to connect or not the VREF+ pin. Refer to Table196: VREF buffer modes for the mode descriptions depending on ENVR bit configuration.
        HIZ: u1,
        reserved3: u1 = 0,
        /// Voltage reference buffer ready
        VRR: u1,
        /// Voltage reference scale These bits select the value generated by the voltage reference buffer. Other: Reserved
        VRS: u3,
        padding: u25 = 0,
    }),
    /// VREFBUF calibration control register
    /// offset: 0x04
    VREFBUF_CCR: mmio.Mmio(packed struct(u32) {
        /// Trimming code These bits are automatically initialized after reset with the trimming value stored in the Flash memory during the production test. Writing into these bits allows to tune the internal reference buffer voltage.
        TRIM: u6,
        padding: u26 = 0,
    }),
};
